# Generated by Django 5.2.6 on 2025-10-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={},
        ),
    ]
