# Generated by Django 5.2.6 on 2025-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_address_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Address",
        ),
    ]
