# Generated by Django 5.2.6 on 2025-10-10 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="default_address",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="nearest_place",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="receive_notifications",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="state",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="street",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="theme_preference",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
