# Generated by Django 5.2.6 on 2025-10-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_address_notification_offer"),
        ("users", "0007_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="applicable_items",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
    ]
