# Generated by Django 5.2.6 on 2025-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="razorpay_signature",
        ),
    ]
