# Generated by Django 5.2.6 on 2025-10-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_razorpay_order_id_and_more"),
        ("users", "0008_customuser_address_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.restaurant",
            ),
        ),
    ]
