# Generated by Django 5.2.6 on 2025-10-12 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reciver_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
